version: "3"

services:
  db:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db

  app:
    build: .
    container_name: url-shortener-app
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  web:
    image: nginx:1.15
    container_name: url-shortener-web
    volumes:
      - ./app:/usr/src/app
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8196:80" # ALTERAR PARA HLG
  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
  #     - PGADMIN_DEFAULT_PASSWORD=admin
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - db