version: "3"

services:
  db:
    image: postgres:latest
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db
    restart: always
    networks:
      - url-shortener-app-network

  app:
    build: .
    container_name: url-shortener-app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - url-shortener-app-network
    restart: always

  web:
    image: nginx:1.15
    container_name: url-shortener-web
    volumes:
      - ./app:/app
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8081:80"
      # - "80:80"
      # - "443:443"
    depends_on:
      - app
    networks:
      - url-shortener-app-network

volumes:
  postgres_data:

networks:
  url-shortener-app-network:
    driver: bridge
